<?php
$sliderData = $this->getSliderData();
$slidesData = Mage::getModel('slider/slider')->getSlidesData($sliderData['id']);
?>
<div class="wrapper1" style="visibility:hidden;">
    <div class="slider-wrapper theme-default" style="position:relative;">
        
        <div <?php if ($slidesData): ?>class="slider nivoSliders"<?php endif; ?>>
            <?php
            foreach ($slidesData as $row):

                $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $row['filename'];
                $var = $row['content'];
                if (strpos($var, 'http://') !== 0 && strpos($var, 'https://') !== 0) {
                    $var = 'http://' . $var;
                }

                $slide_type = Mage::getSingleton('slider/slides')->getTypeArray();
         
                 if($row['filename']  && $slide_type[$row['slide_type']]=='File')
                {
                echo '<a href="' . $var . '"><img src="' . $url . '" alt=""  title="' . $row['title'] . '" /></a>';
                }
           
                if($row['text_heading'] && $slide_type[$row['slide_type']]=='Text')
                {
                 echo '<a href="' . $var . '"  >'.$row['text_heading'].'</a>';
                }
            endforeach;
            ?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery('.slider').nivoSlider({
                    animSpeed: 2000,
                    pauseTime: 5000,
                    effect: 'fade'
                });
                jQuery(".wrapper1").css("visibility", "visible");
            });
        </script>
    </div>
</div>
