	<div class="detail_button">
    <button class="button">New Faviorites</button>                                               
</div> 	
	<?php $featured_products = $this->getFeaturedProducts(); ?>
	<?php shuffle($featured_products); ?>
	<div class="box recently" style="padding-left:15px; padding-right:15px;">
		
		<div class="listing-type-grid  catalog-listing">
			<?php $_collectionSize = count($featured_products) ?>
			<table cellspacing="0" class="recently-list" id="product-list-table">
				<?php 
					$i=0; 
					$j=0;
					foreach ($featured_products as $_res): ?>
					
						<?php $_product = Mage::getModel('catalog/product')->load($_res['product_id']); ?>
						<?php if ($i++%3==0): ?><tr><?php endif ?>
						<?php if ($j++ == 3) break;?>
						
						
						 <div class="product" style="height:360px;width:280px">
                <?php $p_id = $_product->getid(); ?>
                <a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220); ?>"id ="product_image" class="product__image" alt="" ></a> 
                <div class="productname"><?php echo $_product->getName(); ?></div>  
                <div class="description">
                    <?php echo $_product->getShortDescription(); ?>
                </div>
                <div class="price_">                                               
                    <div class="product_price">
                        <?php echo number_format($_product->getPrice(), '1', '.', ',') ?>                                               
                    </div>                                                
                </div>
            </div>
						
						
						
						
						
						<?php if ($i%3==0 && $i!=$_collectionSize): ?></tr><?php endif ?>
					<?php endforeach ?>
 
					<?php for($i;$i%3!=0;$i++): ?>
						<td class="empty-product">&nbsp;</td>
					<?php endfor ?>
					<?php if ($i%3==0): ?>&nbsp;<?php endif ?>
			</table>
			<script type="text/javascript">decorateTable('product-list-table')</script>
		</div>
	</div>
	
	
	<div class="middle">
    <img src="<?php echo $this->getSkinUrl('images/middleimage.jpg') ?>">
    <div class="middle_right_side">
        <div class="visit_button">
            <button class="button">VISIT US</button>                                               
        </div>  
        <div class="studio">
     <p>Our Studio and shop os located at 40 Waltham Street, in the heart of Boston's historic South End</p>                                   
        </div>  
        <div class="timing">
            <p>MONDAY / CLOSED</p>   
            <p>TUESDAY - FRIDAT / 11-6</p>   
            <p>SATURDAY/ 11-7</p> 
            <p>SUNDAY/ 12-5</p>  
            <p>OR BY SPECIAL APPOINTMENT</p>  
        </div>
    </div>
</div>

<div class="bottom">
    <div class="bottom_image">
        <div class="visit_button">
            <button class="button">ABOUT US</button>                                               
        </div> 
 <img src="<?php echo $this->getSkinUrl('images/11.jpg') ?>">
    </div>
    <div class="bottom_image">
        <div class="visit_button">
            <button class="button">BLOG</button>                                               
        </div>
 <img src="<?php echo $this->getSkinUrl('images/12.jpg') ?>"> 
    </div>
    <div class="bottom_image">
        <div class="visit_button">
            <button class="button">PRESS</button>                                               
        </div> 
 <img src="<?php echo $this->getSkinUrl('images/13.jpg') ?>"> 
    </div>
    <div class="bottom_image">
        <div class="visit_button">
            <button class="button">INSTAGRAM</button>    
 <img src="<?php echo $this->getSkinUrl('images/14.jpg') ?>">                                            
        </div> 
    </div>
</div>
