<div class="online_purchase">


  <p id="customer_services"><b>CUSTUMER SERVICES</b></p>
                <p><a href="<?php echo Mage::getUrl('customer-service'); ?>">Jewelry Repair Policy</a></p>
                <p><a href="<?php echo Mage::getUrl('customer/account/login/'); ?>">Ring Size Guide</a></p>
                <p><a href="<?php echo Mage::getUrl('online-purchase'); ?>">Care Instruction</a></p>
                <p><a href="<?php echo Mage::getUrl('about-magento-demo-store'); ?>">Shipping &Delevery  </a></p>
<p><a href="<?php echo Mage::getUrl('about-magento-demo-store'); ?>">Returns Policy</a></p>
                <p><a href="<?php echo Mage::getUrl('about-magento-demo-store'); ?>">In-Store Purchase</a></p>
                <p><a href="<?php echo Mage::getUrl('about-magento-demo-store'); ?>">Privacy Policy</a></p>



</div>
